inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - Guardfile
    - Gemfile
    - spec/**/*
    - db/**/*
    - config/**/*
    - bin/*
